#!/bin/bash

cmake \
    -B build \
    -S vtk \
    -DCMAKE_INSTALL_PREFIX=$INSTALL_PREFIX \
    -DCMAKE_BUILD_TYPE=Release \
    -DBUILD_SHARED_LIBS=ON \
    -DVTK_WRAP_PYTHON=ON \
    -DVTK_PYTHON_VERSION=$PYTHON_VERSION \
    -DVTK_Group_Rendering:BOOL=ON \
    -DVTK_USE_X:BOOL=ON \
    -DBUILD_EXAMPLES:BOOL=OFF \
    -DBUILD_TESTING:BOOL=OFF \
    -DVTK_RENDERING_BACKEND:STRING=OpenGL2 \
    -DCMAKE_BUILD_WITH_INSTALL_RPATH=OFF
