#!/bin/bash

thisdir=$(readlink -f $(dirname $BASH_SOURCE))
. $thisdir/cmake_help.sh
 
declare -A D

D[CMAKE_INSTALL_PREFIX]=$INSTALL_PREFIX
D[CMAKE_BUILD_TYPE]=Release

D[BUILD_SHARED_LIBS]=ON

D[VTK_ENABLE_REMOTE_MODULES]=OFF
D[VTK_BUILD_TESTING]=OFF
D[VTK_BUILD_EXAMPLES]=OFF

D[VTK_WRAP_PYTHON]=ON
D[VTK_PYTHON_VERSION]=3


D[CMAKE_BUILD_WITH_INSTALL_RPATH]=OFF

D[VTK_GROUP_ENABLE_Imaging]=DONT_WANT
D[VTK_GROUP_ENABLE_MPI]=NO
D[VTK_GROUP_ENABLE_Qt]=NO
D[VTK_GROUP_ENABLE_Views]=NO
D[VTK_GROUP_ENABLE_Web]=NO
D[VTK_GROUP_ENABLE_Rendering]=YES

mkdir -p build
cd build
run_cmake D ../vtk
