#!/bin/bash

cmake \
    -B build \
    -S itk \
    -DCMAKE_INSTALL_PREFIX=$INSTALL_PREFIX \
    -DCMAKE_BUILD_TYPE=Release \
    -DBUILD_SHARED_LIBS=ON \
    -DBUILD_EXAMPLES:BOOL=OFF \
    -DBUILD_TESTING:BOOL=OFF \
    -DITK_USE_REVIEW:BOOL=ON \
    -DITK_USE_REVIEW_STATISTICS:BOOL=ON \
    -DITK_USE_OPTIMIZED_REGISTRATION_METHODS:BOOL=ON \
    -DCMAKE_BUILD_WITH_INSTALL_RPATH=OFF
